# Generated by Django 5.0.9 on 2024-09-20 04:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsrciptions', '0006_subscriptions_stripe_id_subscriptionsprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'ordering': ['order', 'featured', '-updated'], 'permissions': [('advanced', 'Advanced Perm'), ('pro', 'Pro Prem'), ('basic', 'Basic Prem')]},
        ),
        migrations.AlterModelOptions(
            name='subscriptionsprice',
            options={'ordering': ['subscriptions__order', 'order', 'featured', '-updated']},
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='featured',
            field=models.BooleanField(default=True, help_text='Featured for frontend'),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='order',
            field=models.IntegerField(default=-1, help_text='Ordeing for frontend'),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subscriptionsprice',
            name='featured',
            field=models.BooleanField(default=True, help_text='Featured for frontend'),
        ),
        migrations.AddField(
            model_name='subscriptionsprice',
            name='order',
            field=models.IntegerField(default=-1, help_text='Ordeing for frontend'),
        ),
        migrations.AddField(
            model_name='subscriptionsprice',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionsprice',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
