# Generated by Django 5.0.9 on 2024-09-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='credits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
