# Generated by Django 5.0.9 on 2024-09-30 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='subscription_paln',
            new_name='subscription_plan',
        ),
    ]
